#!/bin/sh

CONFIG="/etc/mjpeg-cgi/config.xml"
MD5=$CONFIG.md5sum

CAMIP=$(/sbin/dhclient -v wlan0 2>&1 >/dev/null | /bin/grep DHCPACK | /usr/bin/awk '{print $3}')

/bin/sed -r -i.bak 's/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'/$CAMIP/ $CONFIG

if [ ! -f "$MD5" ]
then
  /bin/cat $CONFIG | /usr/bin/md5sum  > $MD5
fi

if /bin/cat $CONFIG | /usr/bin/md5sum -c $MD5 | /bin/grep -qv 'OK'
then
  /bin/systemctl restart mjpeg-cgi.service
fi

